apiVersion: apps/v1

kind: Deployment

metadata:
  name: app-dotnetcore2
  namespace: default
  labels:
    app: app-dotnetcore2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dotnetcore2
  template:
    metadata:
      labels:
        app: app-dotnetcore2

    spec:
      containers:
      - name: app-dotnetcore-ctr
        image: gcr.io/logics-2-0-nonprod/sklearn-iris:0.1
        ports:
        - containerPort: 80
