apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker-1
        image: gcr.io/devsecops-287721/jenkins-docker:v1
        ports:
        - containerPort: 8080
